### ISSUE TITLE
Player Ratings Complete Spreadsheet doesn't match Team Spreadsheet

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#101]
Hi Paige,
Can you check the Main Spreadsheet with all teams: http://basl-manager.herokuapp.com/ratings

vs Cyclones (example): http://basl-manager.herokuapp.com/teams/307/ratings

I don't think it's syncing up: John McEniry is a 12 (new rating) on Cyclones page but is a 13 on All Teams Page.

The all teams page is what i want to submit to reggie

**Comment by PaigePonzeka** [comment]
I think I fixed this do you still see it?

**Comment by Asstcommish** [comment]
Will check and let you know. Thanks!
