### ISSUE TITLE
Logo for All Star Game Announcements

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#104]
Hi Paige,
I sent you some examples of the previous All Star Game logo for print. I think it's time for an upgrade. Can you take a look?

**Comment by PaigePonzeka** [comment]
Hey So we got the old logo what do we want to do from there? I like it a lot but could see how it could use some tweaks, maybe a yellow ball and removing the gray/red? 
![screen shot 2015-06-11 at 10 42 52 am](https://cloud.githubusercontent.com/assets/570818/8109773/a0f53bca-1026-11e5-9d53-b5aa430eac1f.png)

**Comment by Asstcommish** [comment]
That sounds fine! I am open to the change

**Comment by Asstcommish** [comment]
Yes!

**Comment by PaigePonzeka** [comment]
![basl_allstar_logo_v1-3a](https://cloud.githubusercontent.com/assets/570818/8635573/d1fb995c-27f6-11e5-8886-df693af24222.png)

I've updated the logo a bit to fit more with BASL branding.

**Comment by Asstcommish** [comment]
This is awesome .  Thanks
Let's archive the logo, hi res file

Jeff James
Director of A&R
Sony Music Entertainment
Legacy/Commercial Music Group
550 Madison Avenue
Room 1724
New York, NY 10022

Sent from my iPhone

On Jul 11, 2015, at 6:01 PM, Paige Ponzeka <notifications@github.com<mailto:notifications@github.com>> wrote:


[https://cloud.githubusercontent.com/assets/570818/8635573/d1fb995c-27f6-11e5-8886-df693af24222.png]<https://cloud.githubusercontent.com/assets/570818/8635573/d1fb995c-27f6-11e5-8886-df693af24222.png>

I've updated the logo a bit to fit more with BASL branding.

**Comment by PaigePonzeka** [comment]
Done
