### ISSUE TITLE
Unassigned Paid Players

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#108]
Hi Paige,

Can you check if this page is loading properly?
 View Unassigned Paid Players (Opens in New Page)
A list of paid players who have paid their league fees but who haven't been assigned to a team

The query is blank for me

http://basl-manager.herokuapp.com/payments/unassigned

**Comment by PaigePonzeka** [comment]
Was actually looking into something similar with the emails being broken. The way teamsnap is storing the tournament players is break everything. (It creates a second player account :() I don't even want to know what this is going to look like next season. 

Any hoo its all fixed

**Comment by Asstcommish** [comment]
OK. That’s What we should look into.

I believe there is an archive season function. When the season is over. I can test that when Pride Classic is complete.

I also believe once you have a Team Snap Profile, that should be good and you login in to register for the new season.

Do we do something similar with the manager Tool? Start over with each season and archive the old under the year?

**Comment by PaigePonzeka** [comment]
No you'd just create a new season (mark it as active) and get started with your teams. The only thing I would want to make is a way to import the entire season over since a lot of the teams stay the same.

**Comment by Asstcommish** [comment]
That would be a great addition to the tools. Definitely;
