### ISSUE TITLE
Chix with Stix - Fundraiser. Mailchimp? Or Flyer? Facebook?

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#110]
Hi Paige,

From Chix

Hi guys,

The Chix are doing a fundraiser can you please forward the information out to the league?

Thanks

Steph

Begin forwarded message:

From: Gianna Lopreato <glopreato@gmail.com>
Date: June 16, 2015 at 8:54:07 AM EDT
To: BASL Div Rep - Women <mousseau@bigapplesoftball.com>, Tarah Marvell <tarah.marvell@gmail.com>
Cc: Stephanie Loria <dextiny5@aol.com>
Subject: Chix Fundraiser - 2015 FIFA World Cup

Hey Ladies,

The Chix will be running a fundraiser for the 2015 Women's World Cup Bracket play.  These games start this Saturday 6/20.  The Brackets won't be ready to fill out until the last game tomorrow, Wednesday 6/17.

I am using an online pool like last year and will send PayPal instructions to those that sign-up.  Is there any way to get the pool sent out to the league or at least the Team Managers?

Chix with Stix FIFA World Cup 2015 Fundraiser, at PoolTracker.com.  This will only be to predict games in Stage 2 Bracket Play of the 2015 Womens World Cup.

To join, click below and follow the easy steps.   
	
-Click on this link:
	http://www.PoolTracker.com/join.asp?poolid=110736 

-Enter this pool credential information.
	
	The Pool ID is: 110736
	The Pool Password is: chix2015 

Pool entry = $10/entry - payment email will be sent to anyone that registers
You can have unlimited amount of entries.
Depending on the number of participants we may pay out more than just 1st place but 50% of the pool pot will be distributed.
All picks have to be submitted prior to kickoff of the first bracket game, Sat 6/20 @ 4pm EST.
Scoring:
1 point - 1st round correct picks
2 points - 2nd round correct picks
3 points - 3rd round correct picks
4 points - championship game correct pick
Tie-breaker is the total amount of goals in all games of the bracket challenge (final 16 games).  If it is still tied, the final tie-breaker goes to the person that set their picks/tie-breaker first.  The timestamp changes anytime there are adjustments to your picks.

-Make your picks!

Let me know if you need anything else from me and what suggestions you have to pass this around!

Thank you,
Gianna

**Comment by PaigePonzeka** [comment]
Sent you an email with this
