### ISSUE TITLE
Adding DOB Column to Ratings View

### ISSUE THREAD

**Issue by BASLJeff** [BigAppleSoftball/ratingsManager#113]
Hi Paige,
Would it possible to add the date of birth column to the Ratings View

Example: http://basl-manager.herokuapp.com/teams/322/ratings

Also when i create a PDF, it shows the profile # of the player. If nothing can be done to hide it from print, let me know. Otherwise we can leave it

**Comment by PaigePonzeka** [comment]
Where are you creating a PDF of the player? Are you downloading a CSV using the button or trying to print the website? I don't see profile numbers in my downloaded csv

**Comment by Asstcommish** [comment]
Definitely print the PDF not excel

Jeff James
Director of A&R
Sony Music Entertainment
Legacy/Commercial Music Group
550 Madison Avenue
Room 1724
New York, NY 10022

Sent from my iPhone

On Jul 11, 2015, at 5:37 PM, Paige Ponzeka <notifications@github.com<mailto:notifications@github.com>> wrote:


Where are you creating a PDF of the player? Are you downloading a CSV using the button or trying to print the website? I don't see profile numbers in my downloaded csv
