### ISSUE TITLE
ASANA Ratings Tool

### ISSUE THREAD

**Issue by BASLJeff** [BigAppleSoftball/ratingsManager#116]
Paige,

Something to think about. The NAGAAA Ratings tool seems to work well. Can we now tackle ASANA? It’s a little different approach.

20 Questions = 100 points.

NAGAAA was Yes/No = 1/0 per question

ASANA assigns 1-5 per question. So instead of check box, do we now need an drop down with 1-5 or do we have a empty box to enter 1-5 and then tally up total ratings.

I sent you the attachments. I will add to BASL Documents
Jeff

**Comment by PaigePonzeka** [comment]
will that be a tool actually used? Are you responsible for putting in ASANA information? I noticed a lot of the time the Women's division sort of does it own thing. I don't want to spend a lot of time on a tool they won't use.

**Comment by Asstcommish** [comment]
Very good point. The women definitely do the own thing. This is very low priority. I was
Hoping we could use the NAGAAA template but if it's a complete rebuild then this can wait and the spreadsheet on the site is more than enough

Jeff James
Director of A&R
Sony Music Entertainment
Legacy/Commercial Music Group
550 Madison Avenue
Room 1724
New York, NY 10022

Sent from my iPhone

On Jul 11, 2015, at 5:25 PM, Paige Ponzeka <notifications@github.com<mailto:notifications@github.com>> wrote:


will that be a tool actually used? Are you responsible for putting in ASANA information? I noticed a lot of the time the Women's division sort of does it own thing. I don't want to spend a lot of time on a tool they won't use.
