### ISSUE TITLE
Hall of fame image for flyer

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#117]
My hard drive failed yesterday but I will submit a ticket. I think I can do mobile

BASL hall of fame image for flyer. Can you create A hall of fame image.

**Comment by PaigePonzeka** [comment]
Hey sorry what exactly do you want to say in it? 

Nominate Hall of Fame Players? with deadline information?

**Comment by Asstcommish** [comment]
We can close this out. Joe sent a message to the managers

Jeff James
Director of A&R
Sony Music Entertainment
Legacy/Commercial Music Group
550 Madison Avenue
Room 1724
New York, NY 10022

Sent from my iPhone

On Jul 11, 2015, at 5:24 PM, Paige Ponzeka <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey sorry what exactly do you want to say in it?

Nominate Hall of Fame Players? with deadline information?
