### ISSUE TITLE
Fall Ball Logo request

### ISSUE THREAD

**Issue by BASLJeff** [BigAppleSoftball/ratingsManager#118]
Hi Paige,

As the season winds down, Kinda, I would like to create a folder of the BASL logos (fall ball, regular, GSC Pride…) and place it under the webmaster google drive. I remember in the beginning you provided me with a link of all versions. I know I have that somewhere. I am going to start cleaning out the Asstcommish email inbox and moving logos and other web related content to webmaster.

Would you be able to create a Fall Ball Logo with BASL in the Skyline? EPS file. Just thinking ahead to fall ball medals

2 Fall Ball Logos (EPS)

Logo with BASL in the skyline
Logo without BASL in skyline

No rush. Will ticket

Thank you

Jeff

**Comment by PaigePonzeka** [comment]
Done, Transfered all the BASL Documents and Files to the Webmaster Account.

**Comment by BASLJeff** [comment]
Can you send me the Fall ball logo? Or is it in the drive folder
Thanks!

**Comment by BASLJeff** [comment]
Its in the webmaster drive folder that I believe is also shared with you? I
just resent you the invite
