### ISSUE TITLE
Admin Actions - Your Managed Team

### ISSUE THREAD

**Issue by BASL-Webteam** [BigAppleSoftball/ratingsManager#15]
Any way to edit info? under my profile
 Arsenal (Stonewall 2014 Spring)
 gatorz (Rainbow 2014 Spring)
 Bashers (Sachs 2014 Spring)

It's great that KobiBlue had this info. I created the team profiles but then assigned it to the managers. I wasn't on arsenal, gators or bashers. just created the team profile

**Comment by PaigePonzeka** [comment]
Its a little broken but if the team is in an active season (Which You can set from the "Edit Seasons Page" you can edit team rosters and managers and you can remove yourself. 

The thing that is broken is you get multiple warnings when you go to delete a player, just confirm it the first time and refresh the page after and you should be removed. I'm going to create a bug for the delete warning
