### ISSUE TITLE
basl-manager.herokuapp.com - Page error

### ISSUE THREAD

**Issue by BASL-Webteam** [BigAppleSoftball/ratingsManager#16]
Hiya,
I am receiving 500 error when trying to access division payments
http://basl-manager.herokuapp.com/payments/division/27398

**Comment by PaigePonzeka** [comment]
Oops should have told you this: Make sure you go to the "Teamsnap" page and login to teamsnap before you go to division payments... 


Fix: Going to implement a check to make sure you are logged into teamsnap, if not redirect you to the login page

**Comment by BASL-Webteam** [comment]
Nice. I should have known that. Makes sense. I’ll send an update tonight. More payments today
