### ISSUE TITLE
payment scans

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#21]
Please run payment scan every 2 hours

**Comment by PaigePonzeka** [comment]
I'm currently deploying a test that will run it every hour, I turned off VisualPing and am testing this to see if it works. We only get emails when payments are actually received but its still going to run. We should probably just turn it off in the off season

**Comment by PaigePonzeka** [comment]
Okay so currently I have set up a scheduler that runs the payments scans every day and then immediately sends out the roster emails. (Currently I'm running a Monday test to only the web team but I'm thinking Wednesday and Friday Nights if its working fine) 

With that set up I don't think you'll need an update every two hours. 

Lets just keep an eye out for the tests for the automatic emails tomorrow evening
