### ISSUE TITLE
Enhancement: Division Payment Roster

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#24]
Possible Enhancement: ADD Send ALL Divsion Reps Button Would that Work? 

After running the sync, Its been really good to catch the payments.

Option: One button to send to all Division Reps 

Keep the each page active for division by division review.

**Comment by PaigePonzeka** [comment]
Yes this can easily happen, I just didn't want to spam all the Div Reps at first, but if its a useful feature then we can sent out the emails. 

In addition I'd like to explored sending these emails automatically... maybe at 11:00pm Friday Night?

**Comment by Asstcommish** [comment]
Lets try the automation. That would be helpful

**Comment by PaigePonzeka** [comment]
Currently have an automation test for monday, leaving this open since I want to change it to Wed/Fri and also automate sending to the div reps if the tests go well

**Comment by Asstcommish** [comment]
I will send a note to the division reps about automation

Wednesday and Friday seem good! If the division need it, it can be provided upon request

**Comment by PaigePonzeka** [comment]
Automation is looking good minus a few bumps... We hsould get another email Wednesday morning. Lets keep an eye out and open new tickets if we want to change dates, or if we see bugs around it. Going to close this ticket
