### ISSUE TITLE
Jeff Anderson - Paid

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#28]
Can you tell me when Jeff Anderson Paid? Is there a trail
443463 	317571 	April 17, 2015 at 11:11 PM 	Jeff Anderson 	Completed (Paid)
	April 17, 2015 at 11:15 PM 	0 documents 	$90.00

**Comment by Asstcommish** [comment]
I found the Sync Time for Jeff Anderson - Jeff Anderson	12960039	April 26, 2015 at 2:36:13 AM

Is there anything else? If thats it. I'll go with it

**Comment by PaigePonzeka** [comment]
Sometime between April 25 at 3:39:54 PM & April 26 at 2:36:15 AM

The syncs just update the data but don't guarantee a payment time. But I can for sure say before 3:39 on April 25th he was NOT paid

**Comment by Asstcommish** [comment]
Paige: This is great. Thank you

Mike: Just an FYI -

**Comment by Asstcommish** [comment]
Is what a fucking liar the wrong approach to this lol.

**Comment by Asstcommish** [comment]
NO! LOL

Remain your composure. And Know in your mind. That we were CORRECT

Its done. Nobody got hurt on the field. No protest. And the player is paid. This week. I will stress to the division reps to have all managers review the edibility list. I will probably send 1 list at midnight.

Thanks to paige!

Jeff

From: "stonewall@bigapplesoftball.com<mailto:stonewall@bigapplesoftball.com>" <stonewall@bigapplesoftball.com<mailto:stonewall@bigapplesoftball.com>>
Date: Sunday, April 26, 2015 at 10:45 AM
To: Jeff James <jeffrey.james@sonymusic.com<mailto:jeffrey.james@sonymusic.com>>
Cc: "<reply@reply.github.com<mailto:reply@reply.github.com>>" <reply@reply.github.com<mailto:reply@reply.github.com>>, "<ratingsManager@noreply.github.com<mailto:ratingsManager@noreply.github.com>>" <ratingsManager@noreply.github.com<mailto:ratingsManager@noreply.github.com>>, BASL Assistant Commissioner <asstcommish@bigapplesoftball.com<mailto:asstcommish@bigapplesoftball.com>>
Subject: Re: [ratingsManager] Jeff Anderson - Paid (#28)

Is what a fucking liar the wrong approach to this lol.

Sent from my iPhone

On Apr 26, 2015, at 10:18 AM, <Jeffrey.James@sonymusic.com<mailto:Jeffrey.James@sonymusic.com>> <Jeffrey.James@sonymusic.com<mailto:Jeffrey.James@sonymusic.com>> wrote:

Paige: This is great. Thank you

Mike: Just an FYI -

**Comment by PaigePonzeka** [comment]
Did this guy play when he hadn't of paid and then paid the night before and
try to sneak it in?

**Comment by Asstcommish** [comment]
Yes. And to make it worse. The manager of the team is blaming the system and swears that the player registered on the field.

I am so mad, I could spit

**Comment by PaigePonzeka** [comment]
Ahhhhh Mike's Teams always play by the rules ;)

Check the Paypal account. That would be the definitive answer. If paypal
says he registered after the game then he's definitely lying.

either way did you ever say a player could register on the field? I though
you've been saying that they SHOULD be register the NIGHT BEFORE?

**Comment by Asstcommish** [comment]
Lol I will, was just joking 2 out of 4 stonewall mgrs lie. All we need to know for the future.

**Comment by Asstcommish** [comment]
Very good point. This is what the board needs to flesh out. Techincally the BASL by-laws are very vague on Payments and players are waiting until the day of. Even though we are stressing the night before.

We just need to get the by-laws in order

Registration from the By-Laws

5.01 Team Rosters
Addition(s) to the roster may be submitted for each player by using the online registration link on the BASL website. This includes payment of the BASL Membership Fee. This can be done until the roster deadline (the June Governing Body meeting).

8.02 Playoff Rules
A player shall be eligible to participate in the playoffs if he/she has attended at least 50% of regular season games played by his/her team after the player registered.
