### ISSUE TITLE
Player Payments

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#29]
We have two players that paid outside the system. Can we mark them as Paid on the eligibility roster - manually? Create an Edit option?

Nicholas Stansbury
Randy Ovalle

**Comment by PaigePonzeka** [comment]
On Teamsnap.com you need to login and find each players teamsnapId (in the URL), email and first and last name.

Go to the Admin Panel 
Click "View Paid Players" 
Click "+ Add New Payment button"
You enter in the teamsnap ID, Player Name and Email into the form and click "Save"

**Comment by Asstcommish** [comment]
Perfection. Both are updated!
Take a look at the Page: http://basl-manager.herokuapp.com/payments/list/add

Should it be TeamSnap Player ID #? - right now it says TeamSnap Player

In either case, if someone finds me slumped over my computer. I’ll make sure eddie add to my tombstone. Here lies Jeffrey James. Gagged by Paige Ponzeka Brilliance

Thanks

**Comment by PaigePonzeka** [comment]
Yeah its labelled wrong. I'll fix that. Teamsnap Player is Teamsnap Player
Id.

I'll fix that

**Comment by PaigePonzeka** [comment]
Also that made me chuckle ;) thanks!

**Comment by Asstcommish** [comment]
I really like the new Admin Page layout - Home

http://basl-manager.herokuapp.com/admin/home

**Comment by PaigePonzeka** [comment]
Thanks! it was getting a little chaotic was trying to make it a little more
easier to follow. and know where you're going.
