### ISSUE TITLE
Sponsor Carousel on Main Site

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#33]
Can the sponsor carousel be checked - java script? its stopped
thanks

**Comment by PaigePonzeka** [comment]
the javascript was deleted again


remember when you make edits to make sure to go to HTML mode and make sure: 
<script type="text/javascript" src="https://basl-manager.herokuapp.com/assets/basl.js"></script>

is at the bottom of the page

**Comment by Asstcommish** [comment]
It’s there – I placed it in all of the pages so I wouldn’t forget and have access. All the pages stopped. And I only worked on the home page.

I will try it again

<script type="text/javascript" src="https://basl-manager.herokuapp.com/assets/basl.js"></script>

**Comment by PaigePonzeka** [comment]
Its a bug pushing a fix now

**Comment by Asstcommish** [comment]
Whew!! I thought I broke it.
No problem, much appreciated :)
