### ISSUE TITLE
Beavers Fund Raiser flyer template request

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#40]
Let's try this ticket system for request:
Beavers are planning a fundraiser:

Date: TBD
Time: TBD
Location: Branded Saloon (603 Vanderbilt Ave, Brooklyn, NY)
Drink Specials/Raffles: TBD
Logos Needed: Miller Lite, BASL, Beavers, Branded Saloon.

This will be our template request format. Let me know if this works
thanks!

**Comment by PaigePonzeka** [comment]
You want to comment and then tag me in it so I get an email when you get all the details for the flyer?

**Comment by PaigePonzeka** [comment]
(you can tag someone just like you can tag in facebook) it sends me an email so I see it
