### ISSUE TITLE
B-Bombers (Flyer Revision)

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#41]
Nice Flyer! minor revision - address needed for henrietta hudson on flyer. Provided below

hopefully this template will supply the necessary info. Maybe we should set a google form? Simple with the requested info below on a form?

Event: B-Bombers Team Fundraiser
Date: Saturday, May 9th
Time: 1pm - 5pm
Location: Henrietta Hudson (438 Hudson St, New York, NY)
Drink Specials/Raffles: Silent Auction * 50/50 Raffle
Logos Needed: Miller Lite, Henrietta Hudson, BASL, B-Bombers

This will be our template request format. Let me know if this works
thanks!

**Comment by PaigePonzeka** [comment]
oops I forgot to update the flyer! Sorry about that
