### ISSUE TITLE
Comets Team Fundraiser Flyer - Revision

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#43]
Nice Flyer! minor revision - address needed for Monster on flyer. Provided below

Event: Comets Team Fundraiser
Date: Thursday, June 11
Time: 6pm - 9pm
Location: The Monster (80 Grove St, New York, NY)
Drink Specials/Raffles: Drink Specials * 50/50 Raffle
Logos Needed: Miller Lite, Monster, BASL, Comets

This will be our template request format. Let me know if this works
thanks!

**Comment by PaigePonzeka** [comment]
Did the bar request this?
I only add the address to take up white space if I don't have fundraiser details.

**Comment by Asstcommish** [comment]
Oh. GOT it. No, that’s me. Its very old school of me. If it’s not necessary for the sake of space, I’m cool!
