### ISSUE TITLE
Ratings 

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#46]
Hey Paige. 
I don't see the questions for the ratings page? Have they been linked up?

**Comment by PaigePonzeka** [comment]
This has been Complete recording know issues as bugs from now on. If you go to a team page you'll see a "Player Ratings" Button where you can edit a player's ratings with the dialogs. We need to update our account so I can import all the teamsnap data for this season's teams

**Comment by Asstcommish** [comment]
Send me the link to pay for the upgrade. I’ll use a credit card

**Comment by PaigePonzeka** [comment]
Okay Looks like it might take some command work to actually run the update but we do need to connect that credit card. I'll need you go log into heroku with the webteam@bigapplesoftball.com account (the password is in the shared google doc) And go to https://dashboard.heroku.com/account/billing and add the credit card. I can try to do an upgrade some time in the evening after we have a credit card connected. https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrade-with-pgbackups-transfer-default

**Comment by Asstcommish** [comment]
OK. Paige. We should be set. Lets stick with the low plan ($9/month) let me know if everything is OK

**Comment by PaigePonzeka** [comment]
Okay I just upgraded our account and moved over the database. We are looking good
