### ISSUE TITLE
Adding Friends & Family Section to App and Webstie

### ISSUE THREAD

**Issue by PaigePonzeka** [BigAppleSoftball/ratingsManager#5]
Want the ability to manage offers and show them on the basl website as "Friends and Family Section"

1. Website: http://www.aperfectdealer.com
BASL Discount Code: basl
Discount: 10%
https://gm1.ggpht.com/LVjnigdnjsISJJIpwqFNjhjfBlccfQqAHgjLCzGiV65KepxaYfe-cRwmZJ_9Bm_S4Nx9vxjNnlI-Ymh4o3mgmKtufMkjlYV0RiraxJrTRKTFrg0HMsTKslJ7XjVfGUAc5Mu1MdQFQ75vYrTfXqq64rby26-6vosHeMBi2DGYdCJc23fAH8vp-qW4SOsVb-TK6sfxMpJypHBeHNwORGx17CvxZsO47p6kpJ7EgyjBF4tF-Ox_4KYcy0UjqXKnBcd_CIzyxvZ5nUd_oiiATohG67oqDtxC9qNuVL6C3AwitozB-VB7-4WH0oh5T0i2rc-W1sM4OU1G8nZhi2EcRGM0CKbvLEnOVpY2h2ysFNn38WrvWnxHlb9pje21J4IFteFzCjcyALW3KBtRZpYTJFzERXuN9fBFmWoTLiEuWsXVgoM7RzWAMn_yJcClRZTTEBauxf428Z4eD4vY_ifE5GQ0eSovo8iHQ3ChsCLdMKwABDLIq1RqgNT01qIqOG3JWnoi9JpJXPYLVkDfr_0SEDCNQGFv2x4Wnmp8a4capb0h9_6FROhUrEUuA8Edkqj_tAnwcZUjv9heZSbn=s0-l75-ft-l75-ft

2. Website: http://tomboyx.com/account/login
BASL Discount Code: basl10
Discount: 10%
https://gm1.ggpht.com/bjPepKzSucflWSkqy74kTbA87LdSKdbqTtolxPEcv6Jn9NQEY3N8TD7ouTdJjA0EY3ywDx5IooT43R4ntXGwCHDFqoyXc6c8fkiZ6oGdXVIZes3rJrLhWm3fPwUwPl2cljYvldPwBUDrJ8-o0wY30NIAF0ljZ44YGQ7_EVppZjOfcoEpqDHjy6XpARkWOLhm9EOnUqiSFkGAE9xqVUiDGSXWXgwgIYCIDIilZvRxW3VVISzllS3NQWhM3zTiO3rvudUDwat4JwG05gHRjtMkcYwy8sVZ2Z-PEqlFJuTE-EJQB0M6Av7_gP2OoDLEW7u81_jqoDF3gOdVS0zGY-0souRYXItW0zGNxRLwYw9wPdKc6g692qD_VrrkfIRPnNVK-BTPiPcl_OyZN2O6CzajeNvdZNxGrQeqNX7s1xCIyGT9TdOc73KZDDHZjELPGpDLkFoneD0S3t_Ip11TRNi9J2ciDqBKp3XEIhkpz5BnQt2u5539G4H2m1UL89smx1e3dRQjQjrofWAKLIf8CopU9yj8Ie5pf8DmdOOtS8ED9GOQH2sCrBCF9UPs3oDzSllR235UdAh55A=s0-l75-ft-l75-ft

3. Website: www.mets.com/basl
BASL Discount: Reduced price Tickets (Can also contact our rep – Stu Cohen: stucohen@nymets.com)
https://gm1.ggpht.com/8kmQtQtPgJb4sMvazi9eTY_BVXxQFGzO1tp2XbSvvTMDG3WNNoZeBXOa_1e-d9alHKkII4K1E3fwqKc7fgkVGaPycIeONQhka4hI5HZ-0E4T7Zq0XM4mMvjt0XPAQ0zRkqzsrV91bPfzut8EfOv9QUwBnTNkvS_yBCKVlG_JFMGqfS-XkV5fvoEHwKgAh82OckENXQEfmN6qNTYvtWB_3Kz1JrZMbSabx7gZ09w_VcszGicm8NZiv7Hi0O9j8nBHFfwmQ14AzFJz8e4pUq91tFqQ2GoHRdK791FaVsYsaD3VlVBtz9vbG-ezKqVrVKgQKfUDFDXKVe7oveqiasZ2Q2HgLMTWpwtt9q_0NLjiDrORU8T-NbjsNV52Pa5LeWn1W-FpF_X0lM7nK5fiAGeinXiDewAWgRT1-WnBq9HM0WjKppGOIoq9IwrzbFdRjrzrqiZvHsed3NYfa9nLjAYg3x5ZRxUjLlpUJYEcYHUyAkaCjwO19UdXaSLQ8PJiKSdQlgYv7nc70FnrX3vzF_refIVeAf-VsB_qooyRjdN7FJyT5oQB1eQwgTw57AqFf0oEl9NoR8zY70OA=s0-l75-ft-l75-ft

**Comment by BASL-Webteam** [comment]
Can the company name be displayed?

Example
<Image>
Company name
Discount (change field name from Name to Discount) in Editing Offer - http://basl-manager.herokuapp.com/offers/1/edit

**Comment by PaigePonzeka** [comment]
Updated to show the name of the company
Fixed up the Offer image (and also fixed up board_member image), it will look less stretched but you will get stuff cut off if you don't use the correct aspect rations

**Comment by PaigePonzeka** [comment]
OH also added a placeholder and renamed "NAme" to "Discount Name" so its clearer what you should put there
