### ISSUE TITLE
Ratings: Private Setting in TeamSnap

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#75]
In TeamSnap if Ratings Private is clicked, the ratings will not flow to the manager Tool. Can this be override?

Its fine that its private in TeamSnap. But All ratings should flow to the Manager Tool

Jeff

**Comment by PaigePonzeka** [comment]
I'm guessing if a player marks his or her ratings as private The teamsnap api won't return their information to the manager. Do you have an example of a player that is marked as private? Can you see their ratings through the teamsnap admin panel on teamsnap.com
