### ISSUE TITLE
Tried To Update Emergency Contact for Peter DeSouza - Will Not Save

### ISSUE THREAD

**Issue by Asstcommish** [BigAppleSoftball/ratingsManager#94]
Tried To Update Emergency Contact for Peter DeSouza - Will Not Save, Can you check?

http://basl-manager.herokuapp.com/profiles/183

Emergency Contact
Mike Peyton
Friend
917-589-5891

**Comment by PaigePonzeka** [comment]
Oh I can guess whats wrong here. I'll fix that.

**Comment by PaigePonzeka** [comment]
Pushed a Fix for this today
